### ISSUE TITLE
Hint: Be careful with mutable arguments

### ISSUE THREAD

**Issue by ghost** [flodri/py-DMUD#9]
When you add something mutable as a default argument, like a list or a set, like you are doing with the room class, _all_ instances of this class will refer to the same mutable object:

```
>>> class X:
...     def __init__(self, x=set()):
...             self.x = x
... 
>>> a = X()
>>> b = X()
>>> a.x.add(3)
>>> b.x
{3}
```

See here: https://github.com/satwikkansal/wtfpython#-beware-of-default-mutable-arguments

**Comment by flodri** [comment]
I kind of went "hm weird, but it doesn't cause any bugs for now so I'll change that another time" when I first saw your issue. But after re-writing the warn_leave and warn_coming functions and testing them with someone I noticed that it indeed did cause a bug.
Thanks a lot for your issue, otherwise I would still be wondering why the f*ck room.players.add(player_id) was adding the player to all rooms !
Anyway it's fixed now, with a comment pointing here, thanks again.
